Models/Friend.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Facebook.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Friend
    {
        public int Friend_Id { get; set; }
        public string FriendName { get; set; }
        public Nullable<int> UserFriend_Id { get; set; }
        public Nullable<int> User_Id { get; set; }
        public string Status { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}

Controllers/FriendsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.SqlClient;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Facebook.Models;

namespace Facebook.Controllers
{
    public class FriendsController : Controller
    {
        private DemoSMS_OnlienEntities1 db = new DemoSMS_OnlienEntities1();
        static String sql_con = @"Data Source=ADMIN\SQLEXPRESS;Initial Catalog=DemoSMS_Onlien;Integrated Security=True";
        SqlConnection con = new SqlConnection(sql_con);

        // GET: Friends
        public ActionResult Index()
        {
            var users = db.Users.ToList();
           
            var id = Session["UserID"];
            

            //đây là  những người bạn và những người yêu cầu kết bạn
            //List<int> sql3 = db.Friends.Where(f => f.User_Id == (int)id).Select(f => f.Friend_Id).ToList();

            //var sql3 = db.Friends.Where(f => f.User_Id == (int)id).ToList();

            var sqlUser = db.Users.ToList();
            var sqlFriend = db.Friends.ToList();
            

            List<int> listIdFriend = new List<int>();
            List<int> listIdUserFriend = new List<int>();
            List<User> listUser_ChuaAddFriend = new List<User>();

            List<int> idNhungNguoiDangyeuCauKetBan = new List<int>();
            List<int> idNhungNguoiDaDongYKetBan = new List<int>();
            List<int> listNhungNguoiTuChoiKetBan = new List<int>();

            List<User> listUserChuaKetBan = new List<User>();

            List<int> idUserFriend = new List<int>();
            List<int> listUserId = new List<int>();
            foreach (var f in db.Friends)
            {
                idUserFriend.Add((int)f.UserFriend_Id);
                listUserId.Add((int)f.User_Id);
                if (f.Status == null || f.Status.Contains("null") && f.User_Id == (int)id)
                {
                    idNhungNguoiDangyeuCauKetBan.Add((int)f.UserFriend_Id);
                   
                }
                else if (f.Status.Contains("Accepted") && f.User_Id == (int)id)
                    {
                    idNhungNguoiDaDongYKetBan.Add((int)f.UserFriend_Id);
                }
                else if(f.User_Id == (int)id)
                {
                    listNhungNguoiTuChoiKetBan.Add((int)f.UserFriend_Id);
                }
            }
            int count1 = idNhungNguoiDaDongYKetBan.Count();
            int count2 = idNhungNguoiDangyeuCauKetBan.Count();
            int count3 = idUserFriend.Count();
                
            foreach(var u in db.Users)
            { 
                
                var sql = db.Friends.Where(s => s.User_Id == (int)id && s.UserFriend_Id == u.User_Id || s.User_Id == u.User_Id && s.UserFriend_Id == (int)id);
                //if(!(idNhungNguoiDaDongYKetBan.Contains(u.User_Id)) && !(idNhungNguoiDangyeuCauKetBan.Contains(u.User_Id)))
                if (!(idNhungNguoiDaDongYKetBan.Contains(u.User_Id)) && !(sql.Count() > 0))
                {
                    listUserChuaKetBan.Add(u);
                }
                 else
                {
                    //listUserChuaKetBan.Add(u);
                }
            }
            return View(listUserChuaKetBan);
        }
        //var sqlGet = db.Users.Where(s => s.User_Id != f.UserFriend_Id).ToList();
        //var sqlGet = db.Users.Where(s => s.User_Id != f.UserFriend_Id).ToList();
        //var sqlGet2 = db.Users.Where(s => s.Friends.UserFriend_Id != f.UserFriend_Id).ToList();
        //if (f.User_Id != (int)id && idFriend.Contains(f.User_Id))
        //{
        //    listUser_ChuaAddFriend.Add(f);
        //}
        //foreach(var b in sqlGet)
        //{

        //    if(b.User_Id == f.UserFriend_Id)
        //    {
        //        continue;
        //    } 
        //        listUser_ChuaAddFriend.Add(b);


        //}
        //foreach (var b in sqlGet)
        //foreach (var b in sqlUser) // lấy tất cả user
        //{

        //    if (b.User_Id == f.UserFriend_Id)
        //    {
        //        c = false;
        //        continue;
        //    }
        //    else
        //    {
        //        listUser_ChuaAddFriend.Add(b);
        //        c = true;
        //    }
        //}

        //foreach(var i in listUser_ChuaAddFriend)
        //{
        //    if()
        //}


        //List<Friend> listUser_ChuaAddFriend = new List<Friend>();

        //lấy danh sách những người có id không nằm trong list id người bạn và chính mình
        //foreach (var u in db.Users)
        //{
        //    //if (u.User_Id != (int)id && !idFriend.Contains(u.User_Id))
        //    //{
        //    //    listUser_ChuaAddFriend.Add(u);
        //    //}
        //    if (u.User_Id != (int)id && idFriend.Contains(u.User_Id) && idFriend.Contains((int)u.Friend.UserFriend_Id))
        //    {
        //        //listUser_ChuaAddFriend.Add(u);
        //    } else
        //    {
        //        listUser_ChuaAddFriend.Add(u);
        //    }
        //}
        //}




        // GET: Friends/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // GET: Friends/Create
        public ActionResult Create()
        {
            ViewBag.User_Id = new SelectList(db.Users, "User_Id", "UserName");
            ViewBag.UserFriend_Id = new SelectList(db.Users, "User_Id", "UserName");
            return View();
        }

        // POST: Friends/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Friend_Id,FriendName,UserFriend_Id,User_Id")] Friend friend)
        {
            if (ModelState.IsValid)
            {
                db.Friends.Add(friend);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.User_Id = new SelectList(db.Users, "User_Id", "UserName", friend.User_Id);
            ViewBag.UserFriend_Id = new SelectList(db.Users, "User_Id", "UserName", friend.UserFriend_Id);
            return View(friend);
        }

        // GET: Friends/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Friend friend = db.Friends.Find(id);
            if (friend == null)
            {
                return HttpNotFound();
            }
            ViewBag.User_Id = new SelectList(db.Users, "User_Id", "UserName", friend.User_Id);
            ViewBag.UserFriend_Id = new SelectList(db.Users, "User_Id", "UserName", friend.UserFriend_Id);
            return View(friend);
        }

        // POST: Friends/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Friend_Id,FriendName,UserFriend_Id,User_Id")] Friend friend)
        {
            if (ModelState.IsValid)
            {
                db.Entry(friend).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.User_Id = new SelectList(db.Users, "User_Id", "UserName", friend.User_Id);
            ViewBag.UserFriend_Id = new SelectList(db.Users, "User_Id", "UserName", friend.UserFriend_Id);
            return View(friend);
        }

        // GET: Friends/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Friend friend = db.Friends.Find(id);
            if (friend == null)
            {
                return HttpNotFound();
            }
            return View(friend);
        }

        // POST: Friends/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Friend friend = db.Friends.Find(id);
            db.Friends.Remove(friend);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        //public String checkBtnAdd(int UserFriend_Id)
        //{
        //    con.Open();
        //    var a = Session["UserID"];
        //    //string sqlCheck = "select * from Friend where UserFriend_Id = " + UserFriend_Id + " and User_Id = " + a;
        //    var checkTrue = db.Friends.Where(s => s.UserFriend_Id == UserFriend_Id && s.User_Id == (int)a).ToList();
        //    //SqlCommand command = new SqlCommand(checkTrue, con);
        //    //command.ExecuteNonQuery();
        //    int b = checkTrue.Count();
        //    if (checkTrue.Count() > 0)
        //    {
        //        return ViewBag.CheckStatusFriend = "hai bạn đã kết bạn rồi";
        //    }
        //    else
        //    {
        //        return ViewBag.CheckStatusFriend = "hai bạn chưa kết bạn";
        //    }
        //    //return "abc";
        //}

        public ActionResult notications()
        {
            var fen = db.Friends.ToList();
            return View(fen.ToList());
        }

        public String Accept(int User_Id, int UserFriend_Id)
        {
            var a = Session["UserID"];
            con.Open();

Views/Friends/Create.cshtml
@model Facebook.Models.Friend

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
</head>
<body>
    @using (Html.BeginForm()) 
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>Friend</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.FriendName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.FriendName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.FriendName, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.UserFriend_Id, "UserFriend_Id", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("UserFriend_Id", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.UserFriend_Id, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.User_Id, "User_Id", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("User_Id", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.User_Id, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</body>
</html>

Views/Friends/Delete.cshtml
@model Facebook.Models.Friend

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>
    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>Friend</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.FriendName)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.FriendName)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.User.UserName)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.User.UserName)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.User1.UserName)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.User1.UserName)
            </dd>
    
        </dl>
    
        @using (Html.BeginForm()) {
            @Html.AntiForgeryToken()
    
            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                @Html.ActionLink("Back to List", "Index")
            </div>
        }
    </div>
</body>
</html>

Views/Friends/Details.cshtml
@model Facebook.Models.Friend

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Details</title>
</head>
<body>
    <div>
        <h4>Friend</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.FriendName)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.FriendName)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.User.UserName)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.User.UserName)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.User1.UserName)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.User1.UserName)
            </dd>
    
        </dl>
    </div>
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.Friend_Id }) |
        @Html.ActionLink("Back to List", "Index")
    </p>
</body>
</html>

Views/Friends/Index.cshtml
@model IEnumerable<Facebook.Models.User>

@{
    //Layout = "~/Views/Shared/_LayoutFriend.cshtml";
    Layout = null;
}

<!DOCTYPE html>
@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")
@*@RenderSection("scripts", required: false)*@

<style>
    table {
        font-family: arial, sans-serif;
        border-collapse: collapse;
        width: 100%;
    }

    td, th {
        border: 1px solid #dddddd;
        text-align: left;
        padding: 8px;
    }

    td {
        padding: 10px;
    }

    tr:nth-child(even) {
        background-color: #dddddd;
    }

    body {
        margin: 0;
        font-family: "Lato", sans-serif;
    }

    .sidebar {
        margin: 0;
        padding: 0;
        width: 200px;
        background-color: #f1f1f1;
        position: fixed;
        height: 100%;
        overflow: auto;
    }

        .sidebar a {
            display: block;
            color: black;
            padding: 16px;
            text-decoration: none;
        }

            .sidebar a.active {
                background-color: #04AA6D;
                color: white;
            }

            .sidebar a:hover:not(.active) {
                background-color: #555;
                color: white;
            }

    div.content {
        margin-left: 200px;
        padding: 1px 16px;
        height: 1000px;
    }

    .contact-box {
        background: -webkit-linear-gradient(to right, #414345, #232526); /* Chrome 10-25, Safari 5.1-6 */
        background: linear-gradient(to right, #414345, #232526); /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */
        margin-left: -6px;
        width: 100.9%;
        height: 320px;
        margin-top: 450px;
        padding-left: 50px;
    }

        .contact-box p {
            padding-top: 20px;
            font-size: 19px;
            color: #fff;
        }

    .contact-header {
        position: absolute;
    }

    .contact-box .social {
        position: absolute;
        padding-top: 8px;
        margin-left: 70px;
    }

    .contact-box h1 {
        color: #fff;
        font-family: 'Times New Roman', Times, serif;
    }

    .contact-box .social1 {
        position: absolute;
        padding-top: 8px;
        margin-left: 110px;
    }

    ul {
        margin: 0px;
        padding: 0px;
    }

    .footer-section {
        background: #151414;
        position: relative;
    }

    .footer-cta {
        border-bottom: 1px solid #373636;
    }

    .single-cta i {
        color: white;
        font-size: 30px;
        float: left;
        margin-top: 8px;
    }

    .cta-text {
        padding-left: 15px;
        display: inline-block;
    }

        .cta-text h4 {
            color: #fff;
            font-size: 20px;
            font-weight: 600;
            margin-bottom: 2px;
        }

        .cta-text span {
            color: #757575;
            font-size: 15px;
        }

    .footer-content {
        position: relative;
        z-index: 2;
    }

    .footer-pattern img {
        position: absolute;
        top: 0;
        left: 0;
        height: 330px;
        background-size: cover;
        background-position: 100% 100%;
    }

    .footer-logo {
        margin-bottom: 30px;
    }

        .footer-logo img {
            max-width: 200px;
        }

    .footer-text p {
        margin-bottom: 14px;
        font-size: 14px;
        color: #7e7e7e;
        line-height: 28px;
    }

    .footer-social-icon span {
        color: #fff;
        display: block;
        font-size: 20px;
        font-weight: 700;
        font-family: 'Poppins', sans-serif;
        margin-bottom: 20px;
    }

    .footer-social-icon a {
        color: #fff;
        font-size: 16px;
        margin-right: 15px;
    }

    .footer-social-icon i {
        height: 40px;
        width: 40px;
        text-align: center;
        line-height: 38px;
        border-radius: 50%;
    }

    /* .facebook-bg{
      background: white;
    }
    .twitter-bg{
      background: white;
    }
    .google-bg{
      background: white;
    }
    .instagram-bg{
      background: white;
    } */
    .footer-widget-heading h3 {
        color: #fff;
        font-size: 20px;
        font-weight: 600;
        margin-bottom: 40px;
        position: relative;
    }

        .footer-widget-heading h3::before {
            content: "";
            position: absolute;
            left: 0;
            bottom: -15px;
            height: 2px;
            width: 50px;
            background: white;
        }

    .footer-widget ul li {
        display: inline-block;
        float: left;
        width: 50%;
        margin-bottom: 12px;
    }

        .footer-widget ul li a:hover {
            color: white;
        }

        .footer-widget ul li a {
            color: #878787;
            text-transform: capitalize;
        }

    .subscribe-form {
        position: relative;
        overflow: hidden;
    }

        .subscribe-form input {
            width: 100%;
            padding: 14px 28px;
            background: #2E2E2E;
            border: 1px solid #2E2E2E;
            color: #fff;
        }

        .subscribe-form button {
            position: absolute;
            right: 0;
            background: white;
            padding: 13px 20px;
            border: 1px solid white;
            top: 0;
        }

            .subscribe-form button i {
                color: #151414;
                font-size: 22px;
                transform: rotate(-6deg);
            }

    .copyright-area {
        background: #202020;
        padding: 25px 0;
    }

    .copyright-text p {
        margin: 0;
        font-size: 14px;
        color: #878787;
    }

        .copyright-text p a {
            color: #ff5e14;
        }

    .footer-menu li {
        display: inline-block;
        margin-left: 20px;
    }

        .footer-menu li:hover a {
            color: #ff5e14;
        }

        .footer-menu li a {
            font-size: 14px;
            color: #878787;
        }


    /* Green */
</style>
<div class="sidebar">
    <a class="active">@Html.ActionLink("Index", "Index", "Users")</a>
    @Html.ActionLink("Chat", "Chat", "Chat")
    @Html.ActionLink("Add Friend", "Index", "Friends")
    @Html.ActionLink("Notications", "notications", "Friends")
</div>
<head>
    <meta name="viewport" content="width=device-width" />
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
    <link rel="stylesheet" href="./social-media-icons.css">
    <script src="https://kit.fontawesome.com/66aa7c98b3.js" crossorigin="anonymous"></script>

    <title>Index</title>
</head>

<div class="content">
    <div class="haha">
        <table class="table">
            <tr>
                <th>
                    Tên người dùng
                </th>
                <th>
                    Giới tính
                </th>
            </tr>

            @foreach (var item in Model)
            {
                if (item.UserName == Session["UserName"].ToString())
                {
                    <tr style="display:none"></tr>
                }
                else
                {
                    <tr>
                        @*<span> đây là item username @item.UserName</span>
                            <br />
                            <span>đây là session @Session["UserName"].ToString()</span>
                            <br />*@

                        <td>
                            @Html.DisplayFor(modelItem => item.UserName)
                        </td>
                        @if (item.Gender == true)
                        {
                            <td>
                                Male
                            </td>
                        }
                        else
                        {
                            <td>
                                Female
                            </td>
                        }



                        <td id="tdBtn">

                            <button class="addFriendBtn" onclick="addFriend(@item.User_Id, @("'" + item.UserName + "'"))">Add Friend</button>

                            <button class="btnLike" id="likeBtn" onclick="emoji2(@item.User_Id,1)">Like</button>
                            <button id="dislikeBtn" onclick="emoji2(@item.User_Id,0)">Dislike</button>
                            @*@Html.ActionLink("Details", "Details", new { id = item.User_Id })*@

                        </td>


                    </tr>
                }
            }



        </table>
        <script>



            var url = "Friends/Like";
            var url2 = "https://localhost:44315/Friends/Like";
            function emoji2(idLiked, Status) {
                alert("Bạn đã react người này")
                /*var ma = $("#mId").val();*/
                /*alert("data là " + ma);*/
                var url4 = url2 + "?idLiked=" + idLiked + "&Status=" + Status;
                /*debugger*/
                alert(url4);
                $.get(url4, function (data, status) {
                    /*alert("Data: " + data + "\nStatus: " + status);*/
                });

                //change color button
                //var x = document.getElementsByClassName('btnLike').style.backgroundColor = "blue";
                //for (var i = 0; i < x.length; i++) {
                //    x[i].style.backgroundColor = "#205e7a";
                //}
            }
            var urlFriend = "https://localhost:44315/Friends/addFriend";
            var urlCheck = "https://localhost:44315/Friends/checkBtnAdd";
            function addFriend(UserFriend_Id, FriendName) {

                alert("hello đây là function addfriend");
                var url5 = urlFriend + "?UserFriend_Id=" + UserFriend_Id + "&FriendName=" + FriendName;

                $.get(url5, function (data, status) {
                    alert("data: " + data + "\nStatus: " + status);
                })
            }





        </script>
    </div>
</div>

Views/Friends/notications.cshtml
@model IEnumerable<Facebook.Models.Friend>

@{
    Layout = null;
}

<!DOCTYPE html>
@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")

<style>
    table {
        font-family: arial, sans-serif;
        border-collapse: collapse;
        width: 100%;
    }

    td, th {
        border: 1px solid #dddddd;
        text-align: left;
        padding: 8px;
    }

    td {
        padding: 10px;
    }

    tr:nth-child(even) {
        background-color: #dddddd;
    }

    body {
        margin: 0;
        font-family: "Lato", sans-serif;
    }

    .sidebar {
        margin: 0;
        padding: 0;
        width: 200px;
        background-color: #f1f1f1;
        position: fixed;
        height: 100%;
        overflow: auto;
    }

        .sidebar a {
            display: block;
            color: black;
            padding: 16px;
            text-decoration: none;
        }

            .sidebar a.active {
                background-color: #04AA6D;
                color: white;
            }

            .sidebar a:hover:not(.active) {
                background-color: #555;
                color: white;
            }

    div.content {
        margin-left: 200px;
        padding: 1px 16px;
        height: 1000px;
    }



    /* Green */
</style>
<div class="sidebar">
    <a class="active">@Html.ActionLink("Index", "Index", "Users")</a>
    @Html.ActionLink("Chat", "Chat", "Chat")
    @Html.ActionLink("Add Friend", "Index", "Friends")
    @Html.ActionLink("Notications", "notications", "Friends")
</div>
<head>


    <title>notications</title>
    <meta name="viewport" content="width=device-width" />
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
    <link rel="stylesheet" href="./social-media-icons.css">
    <script src="https://kit.fontawesome.com/66aa7c98b3.js" crossorigin="anonymous"></script>
</head>
<div class="content">
    <div class="haha">
        <table class="table">
            <tr>
                <th>
                    Người gửi 
                </th>
                <th>
                    Người nhận
                </th>
                <th>
                   Trạng thái bạn bè
                </th>

            </tr>
            @foreach (var item in Model)
            {
                if (item.FriendName == Session["UserName"].ToString() || item.User.UserName == Session["UserName"].ToString())
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.User.UserName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.FriendName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Status)
                        </td>
                        <td>
                            @if (item.Status == "Accepted")
                            {
                                <span>2 bạn đã trở thành bạn bè </span>
                            }
                            @if (item.Status == "Refused" || item.Status == "Accepted")
                            {
                            <td style="display:none"></td>
                        }
                        else
                        {
                            if (item.User.UserName == Session["UserName"].ToString())
                            {
                                <td style="display:none"></td>
                            }
                            else
                            {
                                <button id="acceptBtn" onclick="accept(@item.User_Id,@item.UserFriend_Id)">Accept</button>
                                <button id="dislikeBtn" onclick="decline(@item.User_Id,@item.UserFriend_Id)">Decline</button>
                            }

                        }
                            </td>


                        </tr>
                    }
                }


        </table>

        <script>
            var url = "Friends/Accept";
            var url2 = "https://localhost:44315/Friends/Accept";
            function accept(User_Id, UserFriend_Id) {
                var url4 = url2 + "?User_Id=" + User_Id + "&UserFriend_Id=" + UserFriend_Id;
                /*alert(url4);*/
                var r = confirm("Bạn có muốn kết bạn với người này không!");
                if (r == true) {
                    $.get(url4, function (data, status) {
                        alert("Data: " + data + "\nStatus: " + status);
                        location.reload();
                    });
                } else {

                }
            }

            var url3 = "https://localhost:44315/Friends/Decline";
            function decline(User_Id, UserFriend_Id) {
                var url4 = url3 + "?User_Id=" + User_Id + "&UserFriend_Id=" + UserFriend_Id;
                //alert(url4);
                var r = confirm("Bạn có muốn từ chối người này không!");
                if (r == true) {
                    $.get(url4, function (data, status) {
                        alert("Data: " + data + "\nStatus: " + status);
                        location.reload();
                    });
                } else {

                }
            }
        </script>
    </div>
</div>